export const toolboxObj = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'My Toolbox',
  headline: 'Languages & Skills',
  skill1: `Javascript`, 
  skill2: `Python`,
  skill3: `HTML/CSS`,
  skill4: `Node.js`,
  skill5: `React`,
  skill6: `Postgres`,
  skill7: `MySQL`,
  skill8: `RESTful APIs`,
  skill9: `AJAX`,
  skill10: `Security Concepts`,
  skill11: `Websockets/Network Protocols`,
  buttonLabel: `To Projects`,
  imgStart: true,
  dark: true,
  primary: true,
  darkText: true
}